force-app/main/default/objects/iManageSettings__c/iManageSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>iManageSettings</label>
</CustomObject>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>GDSI iManage package logger file</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>LogId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description
  >Log text value (Should have more than one log entry, because here exist some issue with count of queries per request)</description>
    <label>Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Logger.cls
global class Logger extends LoggerBase {
  private static Logger instance = null;

  private Logger() {
    iManageSettings__c mc = iManageSettings__c.getOrgDefaults();
    LogObject = 'gdsi_imanage__Log__c';
    Enabled = mc.gdsi_imanage__Verbose_Logging__c;
  }

  global static Logger getInstance() {
    if (instance == null) {
      instance = new Logger();
    }
    return instance;
  }

  public override Void InsertDBLog(string message) {
    Log__c log = new Log__c();
    log.Value__c = message;
    insert log;
  }
}