force-app/main/default/objects/IManage_File_Link__c/IManage_File_Link__c.object-meta.xml
<CustomObject>
    <description>Links to iManage Files</description>
    <label>IManage File Link</label>
    <nameField>
        <displayFormat>IFL-{0000}</displayFormat>
        <label>IManage File Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IManage File Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IManage_File_Link__c/fields/File_Link__c.field-meta.xml
<CustomField>
    <fullName>File_Link__c</fullName>
    <label>File Link</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/IManage_File_Link__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>ParentId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IManage_File_Link__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IManageLinksAndFilesHelper.cls
public with sharing class IManageLinksAndFilesHelper {
  @AuraEnabled
  public static List<IManage_File_Link__c> getLinks(
    String parentId,
    Integer size,
    Integer skip
  ) {
    List<IManage_File_Link__c> result = [
      SELECT Id, LastModifiedDate, Name, File_Link__c, ParentId__c, Version__c
      FROM IManage_File_Link__c
      WHERE ParentId__c = :parentId
      LIMIT :size
      OFFSET :skip
    ];
    return result;
  }

  @AuraEnabled
  public static Integer getLinksCount(String parentId) {
    Integer result = [
      SELECT COUNT()
      FROM IManage_File_Link__c
      WHERE ParentId__c = :parentId
    ];
    return result;
  }

  @AuraEnabled
  public static List<SObject> getFiles(
    String parentId,
    Integer size,
    Integer skip
  ) {
    List<SObject> result = [
      SELECT
        ContentDocumentId,
        LinkedEntityId,
        ContentDocument.id,
        ContentDocument.LastModifiedDate,
        ContentDocument.title,
        ContentDocument.FileExtension,
        ContentDocument.ContentModifiedDate
      FROM ContentDocumentLink
      WHERE LinkedEntityId = :parentId
      LIMIT :size
      OFFSET :skip
    ];
    return result;
  }

  @AuraEnabled
  public static Integer getFilesCount(String parentId) {
    Integer result = [
      SELECT COUNT()
      FROM ContentDocumentLink
      WHERE LinkedEntityId = :parentId
    ];
    return result;
  }
}