force-app/main/default/objects/IManageMapping__c/IManageMapping__c.object-meta.xml
<CustomObject>
    <label>IManageMapping</label>
    <nameField>
        <label>IManageMapping__c Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IManageMappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IManageMapping__c/fields/ClientIdField__c.field-meta.xml
<CustomField>
    <fullName>ClientIdField__c</fullName>
    <label>ClientIdField</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IManageMapping__c/fields/ClientNameField__c.field-meta.xml
<CustomField>
    <fullName>ClientNameField__c</fullName>
    <description>ClientName Field</description>
    <label>ClientNameField</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IManageMapping__c/fields/EntityClientIdObjectField__c.field-meta.xml
<CustomField>
    <fullName>EntityClientIdObjectField__c</fullName>
    <label>EntityClientIdObjectField</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IManageMapping__c/fields/EntityMatterIdObjectField__c.field-meta.xml
<CustomField>
    <fullName>EntityMatterIdObjectField__c</fullName>
    <label>EntityMatterIdObjectField</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IManageMapping__c/fields/EntityType__c.field-meta.xml
<CustomField>
    <fullName>EntityType__c</fullName>
    <label>EntityType</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/IManageMapping__c/fields/MatterIdField__c.field-meta.xml
<CustomField>
    <fullName>MatterIdField__c</fullName>
    <label>MatterIdField</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IManageMapping__c/fields/MatterNameField__c.field-meta.xml
<CustomField>
    <fullName>MatterNameField__c</fullName>
    <description>MatterName Field</description>
    <label>MatterNameField</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IManageCsvEndpointTests.cls
@isTest
public class IManageCsvEndpointTests {
  @isTest
  static void testGetPositive() {
    // Create mappoing
    IManageMapping__c mapping = new IManageMapping__c(
      EntityType__c = 'Opportunity',
      EntityMatterIdObjectField__c = 'Opportunity',
      MatterIdField__c = 'Id',
      MatterNameField__c = 'Name',
      EntityClientIdObjectField__c = 'AccountId',
      ClientIdField__c = 'Id',
      ClientNameField__c = 'Name'
    );
    insert mapping;

    // Create Account
    Account acc = new Account(Name = 'Donald Duck');
    insert acc;

    // Create oppporunity
    Opportunity opp = new Opportunity(
      AccountId = acc.Id,
      Name = 'Test Opportunity Name',
      StageName = '100',
      CloseDate = system.now().addDays(30).date()
    );
    insert opp;

    RestRequest req = new RestRequest();
    RestResponse res = new RestResponse();
    String dateFormat = 'yyyy-MM-dd HH:mm:ss';

    req.requestURI = '/services/apexrest/gdsi_imanage/IManageCsv';
    req.httpMethod = 'GET';
    req.addParameter('objectName', 'Opportunity');
    req.addParameter('separator', ',');
    req.addParameter('startDate', '2021-12-31 00:00:00.000+0000');
    req.addParameter('endDate', system.now().addDays(1).format(dateFormat));

    RestContext.request = req;
    RestContext.response = res;

    Test.startTest();
    String result = IManageCsvEndpoint.doGet();
    Test.stopTest();

    System.assertNotEquals('', result);
    System.assertEquals(null, res.statusCode);
  }

  @isTest
  static void testGetWithoutRequiredParameter() {
    RestRequest req = new RestRequest();
    RestResponse res = new RestResponse();

    req.requestURI = '/services/apexrest/gdsi_imanage/IManageCsv';
    req.httpMethod = 'GET';
    req.addParameter('separator', ',');
    req.addParameter('startDate', '2021-12-31 00:00:00.000+0000');
    RestContext.request = req;
    RestContext.response = res;

    Test.startTest();
    String result = IManageCsvEndpoint.doGet();
    Test.stopTest();

    System.assertEquals('', result);
    System.assertEquals(400, res.statusCode);
  }
}